### ISSUE TITLE
Sending commands via RS485 fails

### ISSUE THREAD

**Issue by janrothkegel** [syssi/esphome-soyosource-gtn-virtual-meter#148]
Hi,

I use the following board in order to communicate with the SoyoSource: [Link](https://www.amazon.de/gp/product/B07DJ4TGY3/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

However, the connector is shown as not connected and only the TXD LED of the board flashes:

![grafik](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/52739230/ce84a9cd-7dfc-4e00-bc87-bb120ef77a5d)

Is there a chance that I did a mistake?

Thanks in advance
Jan

**Comment by syssi** [comment]
Which Soyosource model do you own? Could you provide the color of the mainboard, too. It's the WiFi version, correct? This device doesn't respond to RS485 messages. Flashing of the TX LED only is fine here.

Do you own the original limiter clamp? Please connect the clamp to your Soyosource and check the `limiter connected` binary sensor again. Is your device able to receive power demand frames in general?

**Comment by janrothkegel** [comment]
I have a 1000W WiFi version with purple mainboard. Unfortunately I cannot check using the original limiter at the moment as I soldered it to the RS485 communication module. I will try to build a separate cable for testing.

Thank you so far.

**Comment by janrothkegel** [comment]
I built a new cable, but I was not aware that I need to connect the limiter to the grid (which is something that I will not do).

I attached a video, just to confirm that we talk about the same thing when we refer to "flashing LED".

https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/52739230/8257cbca-9568-44b4-bc86-81d651720238

**Comment by syssi** [comment]
Lol. Good catch! This isn't the LED I was talking about. The RS485 converter has a RX and TX LED. The `TXD` one should flash. May be your ESP is constantly crashing. Please take look at the log output of the serial interface.

**Comment by janrothkegel** [comment]
But the right one is my converter (the one that I mentioned in my initial post). And the LED on this board/converter is labeled "TXD". Do I miss something? :-/

**Comment by syssi** [comment]
I wasn't awake this morning and it looks like I was confused from the flashing of your ESP. Your RS485 converter blinks too and this is important because it indicates the outgoing traffic of your ESP. Do you have to chance to attach a second RS485 converter and ESP to retrieve he current setup and dump the incoming traffic of the other side? I could provide a YAML to dump the traffic.

**Comment by janrothkegel** [comment]
I am a little bit torn now.

- Most probably I will go for a simpler solution where I will run on constant power.
- On the other hand: This sounds so cool ^^

Out of curiosity, I would like to run this experiment in case you are free (I don't want to block you from doing something more important). And it will take some time as I will need to order some ESP32s from China :-)

**Comment by syssi** [comment]
The experiment doesn't cost me much effort. Please use this YAML for the receiving ESP: https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/main/tests/esp8266-limiter-rx.yaml

The setup should look like this:

```
ESP1 <--RX/TX--> RS485 converter1 <--A/B--> RS485 converter2 <--RX/TX--> ESP2
```

The ESP1 will publish the power demand periodically. The TX LED of the "RS485 converter1" should blink periodically. On the second RS485 converter the RX LED should blink periodically and the received frame should be printed to the log.

**Comment by janrothkegel** [comment]
It turned out that the wires at the RS485 plug were swapped in my case. Now things work out perfectly.

Thanks for your great documentation!

![grafik](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/52739230/a0aa81ae-e517-45dc-a4bf-5983d9194210)
