### ISSUE TITLE
Invalid header: 0x40 0x20 0xC0 0xC

### ISSUE THREAD

**Issue by WZBFL** [syssi/esphome-soyosource-gtn-virtual-meter#151]
A lot of error Messages here:

![2023-08-16 09_29_32-soyosource](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/102554708/e25a4d4c-4991-4630-b631-052556cea228)

**Comment by syssi** [comment]
Could you describe your setup and provide another log (with `uart` debugging enabled: https://github.com/syssi/esphome-soyosource-gtn-virtual-meter#debugging) in plaintext?

**Comment by WZBFL** [comment]
no Problem:

![2023-08-16 09_29_32-soyosource](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/102554708/b3470c8a-5c21-4b99-9927-c1aec6bca9ea)

**Comment by syssi** [comment]
Could you describe the connection/wires between the ESP and the limiter port of your soyosource? How long is the cable? Which RS485 converter module do you use? Is there something else connected to the bus? A photo would be nice. For now it looks like there is some noise/garbage on the bus.
