### ISSUE TITLE
no power value for virtualmeter

### ISSUE THREAD

**Issue by wasn-eu** [syssi/esphome-soyosource-gtn-virtual-meter#153]
i have installed the esp8266-display-display-version-limiter-example.yaml on an esp8266 and connected it to the rs485 and display port.
the display port functions are ok, but why do it not see a value for sensor.soyodisplay_soyosource_gtn_display_power_demand?
i have set the right sensor in the yaml file and i am using the api.

the binary_sensor.soyodisplay_soyosource_gtn_display_limiter_connected is on.

this is what i see in the esphome logs:

> [22:28:58][I][soyosource_display:235]: Status frame (Soyo, 15 bytes) received    
> [22:28:58][I][soyosource_display:386]: Settings (Soyo, 15 bytes):    
> [22:28:58][I][soyosource_display:399]:   Operation mode setting: 16 (0x10)    
> [22:28:58][I][soyosource_display:412]:   Device model: 1000 W (210)    
> [22:28:58][I][soyosource_display:415]:   Device type: PV 26-56V / BAT 24V (24)    
> [22:28:58][I][soyosource_display:419]:   Start voltage: 25 V    
> [22:28:58][I][soyosource_display:425]:   Shutdown voltage: 23 V    
> [22:28:58][I][soyosource_display:439]:   Output power limit: 50 W    
> [22:28:58][I][soyosource_display:445]:   Start delay: 6 s

i have attached my esphome config
[soyodisplay.txt](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/files/12528290/soyodisplay.txt)

an other problem is that there is always the error "DC Voltage tom low" but i have a shutdown voltage of 23V and startup voltage of 25V and my battery is full loaded with 28.8V

**Comment by wasn-eu** [comment]
i have changed the sensor for reporting the output demand and now it is working

**Comment by syssi** [comment]
Good job!
