### ISSUE TITLE
Using without RS485 board

### ISSUE THREAD

**Issue by poky** [syssi/esphome-soyosource-gtn-virtual-meter#159]
Hi, I have a display version 24V 1000W, FW STC8-23-0130 with not RS485 board.
However, the RS485 header is there (5pin with tx,rx, 5V, GND), is it possible to get it to communicate directly without the RS485?
Could anyone direct me how to do it? Thanks!

**Comment by syssi** [comment]
Is my understanding correctly: These components (RS485 converter and connector board) are missing?

![rs485-module](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/2735933/534421a2-f8fc-4867-a3db-816093422c9f)

**Comment by poky** [comment]
Yes, Correct!
![90393](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/138415/d9ed31aa-dcff-47b6-9223-7a77beed08b7)

**Comment by syssi** [comment]
Please don't attach a ESP directly. You should use a digital isolator module (ADUM1201). The setup will look like this:

https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/main/docs/display-version/isolated-data-cable.jpg

Without the JST connector. Don't expect a response if you send instructions (a power demand).

**Comment by poky** [comment]
> Please don't attach a ESP directly. You should use a digital isolator module (ADUM1201). The setup will look like this:
> 
> https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/blob/main/docs/display-version/isolated-data-cable.jpg
> 
> Without the JST connector. Don't expect a response if you send instructions (a power demand).

I currently don't have ADUM lying around, can I get away with it if power from the 5V to VIN, and 1k resistor on both RX, TX?

**Comment by poky** [comment]
> It's normal if your firmware / model doesn't respond to status requests on the RS485 bus. In limiter mode the Soyosource should respect the power demands transmitted using RS485 nevertheless.

Yes, I can see the blue RS485 icon shows up when sending the power demands, so I think it works fine directly without the messy rs485 conversion.

![Screenshot 2023-12-01 at 9 20 18 AM](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/138415/009a0a56-34ac-4ac2-9ddb-80803013b490)
