### ISSUE TITLE
Separate status reports for the multiple Inverters on a single bus

### ISSUE THREAD

**Issue by yury-sannikov** [syssi/esphome-soyosource-gtn-virtual-meter#167]
Hi @syssi.
First of all, than you for such a great project!

Do you know if it's possible to set different addresses on the inverters and receive individual statuses?
While it's perfectly fine to send broadcast power request to the multiple inverters I'm interested in receiving individual statuses.
I see the address field is fixed to the 0x23, not sure if other fields can be used as a discriminator for this case.

I do not have an inverter yet, so I can't test it on my own.

Here is the reference to the documentation:
![image](https://github.com/syssi/esphome-soyosource-gtn-virtual-meter/assets/6585448/59219875-3a83-47c0-b7ba-785601a3ce56)

**Comment by syssi** [comment]
I cannot help here. These specific protocol details of the Soyosource are a mystery.
