### ISSUE TITLE
soyosource_modbus need a name now

### ISSUE THREAD

**Issue by IceOnly** [syssi/esphome-soyosource-gtn-virtual-meter#43]
I got the following error:

```
soyosource_modbus: [source /config/esphome/soyosource.yaml:37]
  
  'name' is a required option for [0].
  - [source /config/esphome/soyosource.yaml:37]
    {}
```

There is this name used for?
Can i change 
```
soyosource_modbus:
```
to
```
soyosource_modbus:
   name: ${name}
```

Would be nice if the readme will be updated :)

**Comment by syssi** [comment]
The name is used as prefix for the log messages. If you have multiple inverters the prefix/name is helpful to distinguish between the different devices.

**Comment by syssi** [comment]
I've added a default (name: "unnamed") now to avoid the breaking change and disturbing more people. :-)
