### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dowermyr** [syssi/esphome-soyosource-gtn-virtual-meter#75]
Hi! Never installed a custom component for esphome in Home Assistant before.
How do I do this?

**Comment by syssi** [comment]
If this instruction is part of your configuration yaml

```
external_components:
  - source: github://syssi/esphome-soyosource-gtn-virtual-meter@main
    refresh: 0s
```

ESPHome will care about everything.

**Comment by dowermyr** [comment]
I get this:

Integration error: external_components - Integration 'external_components' not found.

**Comment by syssi** [comment]
Please make sure you are using a recent ESPHome Release. A lot of Home Assistant users didn't migrate to the official ESPHome integration.
